import type { GpuCardDto, ProcessRowDto } from '../lib/types';

export const makeProcessRow = (overrides: Partial<ProcessRowDto> = {}): ProcessRowDto => ({
  serverId: 'alpha',
  serverName: 'Alpha Node',
  stale: false,
  gpuIndex: 0,
  pid: 100,
  parentPid: null,
  runtimeSeconds: null,
  username: 'alice',
  command: 'python train.py',
  gpuUuid: 'GPU-alpha-0',
  processKind: 'compute',
  gpuMemoryUsedMiB: 1024,
  gpuUtilizationPercent: 10,
  gpuSmUtilizationPercent: 10,
  gpuMemoryUtilizationPercent: 10,
  gpuEncoderUtilizationPercent: null,
  gpuDecoderUtilizationPercent: null,
  cpuPercent: 1,
  hostMemoryUsedMiB: 1,
  ...overrides
});

export const gpuCardFixture: GpuCardDto = {
  index: 0,
  uuid: 'GPU-1111',
  name: 'NVIDIA RTX 6000',
  pciBusId: '0000:17:00.0',
  driverVersion: '550.54',
  graphicsClockMhz: 1740,
  memoryClockMhz: 9501,
  busy: false,
  memoryTotalMiB: 24576,
  memoryUsedMiB: 0,
  memoryFreeMiB: 24576,
  gpuUtilizationPercent: 0,
  memoryUtilizationPercent: 0,
  temperatureCelsius: 32,
  powerDrawWatt: 42.5,
  powerLimitWatt: 300,
  fanSpeedPercent: 18,
  processCount: 0,
  processes: []
};

export const visibilityProcessRows: ProcessRowDto[] = [
  makeProcessRow({
    serverId: 'alpha',
    serverName: 'Alpha Node',
    gpuIndex: 1,
    pid: 100,
    command: 'python train.py --token=supersecret --output /Users/alice/projects/checkpoint.bin',
    gpuUuid: 'GPU-alpha-1',
    gpuMemoryUsedMiB: 2048,
    gpuUtilizationPercent: 90,
    cpuPercent: 12,
    hostMemoryUsedMiB: 1024
  }),
  makeProcessRow({
    serverId: 'alpha-clone',
    serverName: 'Alpha Node',
    gpuIndex: 1,
    pid: 100,
    command: 'python train.py --token=supersecret --output /Users/alice/projects/checkpoint.bin',
    gpuUuid: 'GPU-alpha-1',
    gpuMemoryUsedMiB: 2048,
    gpuUtilizationPercent: 90,
    cpuPercent: 12,
    hostMemoryUsedMiB: 1024
  }),
  makeProcessRow({
    serverId: 'beta',
    serverName: 'Beta Node',
    stale: true,
    gpuIndex: 0,
    pid: 200,
    username: null,
    command: `python render.py ${'x'.repeat(120)} hidden-tail-marker`,
    gpuUuid: 'GPU-beta-0',
    processKind: 'graphics',
    gpuMemoryUsedMiB: 2048,
    gpuUtilizationPercent: null,
    cpuPercent: null,
    hostMemoryUsedMiB: null
  }),
  makeProcessRow({
    serverId: 'gamma',
    serverName: 'Gamma Node',
    stale: false,
    gpuIndex: 2,
    pid: 300,
    username: 'carol',
    command: null,
    gpuUuid: 'GPU-gamma-2',
    processKind: 'unknown',
    gpuMemoryUsedMiB: 512,
    gpuUtilizationPercent: 10,
    cpuPercent: 1,
    hostMemoryUsedMiB: 256
  }),
  makeProcessRow({
    serverId: 'delta',
    serverName: 'Delta Node',
    stale: false,
    gpuIndex: 3,
    pid: 400,
    username: 'dave',
    command: 'python final.py',
    gpuUuid: 'GPU-delta-3',
    gpuMemoryUsedMiB: null,
    gpuUtilizationPercent: 0,
    cpuPercent: 0,
    hostMemoryUsedMiB: 0
  })
];

export const processTableRows: ProcessRowDto[] = [
  makeProcessRow({
    serverId: 'server-low',
    serverName: 'Low memory host',
    gpuIndex: 1,
    pid: 2002,
    runtimeSeconds: 3723,
    username: 'bob',
    command: 'python worker.py',
    gpuUuid: 'GPU-low-1',
    gpuMemoryUsedMiB: 512,
    gpuUtilizationPercent: 35,
    gpuSmUtilizationPercent: 28,
    gpuMemoryUtilizationPercent: 16,
    gpuEncoderUtilizationPercent: 0,
    gpuDecoderUtilizationPercent: 0,
    cpuPercent: 8.5,
    hostMemoryUsedMiB: 1024
  }),
  makeProcessRow({
    serverId: 'server-high',
    serverName: 'High memory host',
    stale: true,
    gpuIndex: 0,
    pid: 1001,
    username: null,
    command: null,
    gpuUuid: 'GPU-high-0',
    processKind: 'unknown',
    gpuMemoryUsedMiB: 4096,
    gpuUtilizationPercent: null,
    gpuSmUtilizationPercent: null,
    gpuMemoryUtilizationPercent: null,
    gpuEncoderUtilizationPercent: null,
    gpuDecoderUtilizationPercent: null,
    cpuPercent: null,
    hostMemoryUsedMiB: null
  }),
  makeProcessRow({
    serverId: 'server-render',
    serverName: 'Render host',
    gpuIndex: 2,
    pid: 1500,
    parentPid: 1499,
    runtimeSeconds: 59,
    username: 'ada',
    command: 'blender --background scene.blend',
    gpuUuid: 'GPU-render-2',
    processKind: 'graphics',
    gpuMemoryUsedMiB: 2048,
    gpuUtilizationPercent: 82,
    gpuSmUtilizationPercent: 77,
    gpuMemoryUtilizationPercent: 63,
    gpuEncoderUtilizationPercent: 11,
    gpuDecoderUtilizationPercent: 12,
    cpuPercent: 22.5,
    hostMemoryUsedMiB: 4096
  }),
  makeProcessRow({
    serverId: 'server-low',
    serverName: 'Low memory host',
    gpuIndex: 0,
    pid: 3003,
    parentPid: 2002,
    runtimeSeconds: 3661,
    username: 'carol',
    command: 'python trainer.py --token=supersecret',
    gpuUuid: 'GPU-low-0',
    gpuMemoryUsedMiB: 1024,
    gpuUtilizationPercent: 48,
    gpuSmUtilizationPercent: 47,
    gpuMemoryUtilizationPercent: 24,
    gpuEncoderUtilizationPercent: null,
    gpuDecoderUtilizationPercent: 2,
    cpuPercent: 14,
    hostMemoryUsedMiB: 2048
  }),
  makeProcessRow({
    serverId: 'server-batch',
    serverName: 'Batch host',
    stale: true,
    gpuIndex: 3,
    pid: 4004,
    runtimeSeconds: 0,
    username: 'drew',
    command: 'sleep 30',
    gpuUuid: 'GPU-batch-3',
    processKind: 'utility',
    gpuMemoryUsedMiB: 256,
    gpuUtilizationPercent: 3,
    gpuSmUtilizationPercent: 1,
    gpuMemoryUtilizationPercent: 2,
    gpuEncoderUtilizationPercent: 3,
    gpuDecoderUtilizationPercent: 4,
    cpuPercent: 1,
    hostMemoryUsedMiB: 512
  })
];

export const apiProcessRow = makeProcessRow({
  serverId: 'server-2',
  serverName: 'Saved GPU',
  gpuIndex: 0,
  pid: 1234,
  runtimeSeconds: 60,
  username: 'alice',
  command: 'python train.py',
  gpuUuid: 'GPU-1',
  gpuMemoryUsedMiB: 1024,
  gpuUtilizationPercent: 75,
  gpuSmUtilizationPercent: 70,
  gpuMemoryUtilizationPercent: 25,
  gpuEncoderUtilizationPercent: null,
  gpuDecoderUtilizationPercent: null,
  cpuPercent: 20,
  hostMemoryUsedMiB: 2048
});
